cmake_minimum_required(VERSION 3.0)

set(CMAKE_SYSTEM_NAME VxWorks)

set(CMAKE_SYSTEM_PROCESSOR $ENV{WIND_SDK_TARGET})
set(CMAKE_SYSTEM_VERSION 1)


set(CMAKE_GENERATOR "Unix Makefiles")
set(CMAKE_MAKE_PROGRAM "/usr/bin/make" CACHE INTERNAL "" FORCE) 

set(CMAKE_CROSSCOMPILING TRUE)

set(CMAKE_LINKER       $ENV{WIND_TARGET_PROC}-wrs-vxworks-ld CACHE INTERNAL "" FORCE)
set(CMAKE_AR           $ENV{WIND_TARGET_PROC}-wrs-vxworks-ar CACHE INTERNAL "" FORCE)
set(CMAKE_C_COMPILER   $ENV{WIND_TARGET_PROC}-wrs-vxworks-cc)
set(CMAKE_CXX_COMPILER $ENV{WIND_TARGET_PROC}-wrs-vxworks-cxx)

set(CMAKE_NM           $ENV{WIND_TARGET_PROC}-wrs-vxworks-nm)
set(CMAKE_STRIP        $ENV{WIND_TARGET_PROC}-wrs-vxworks-strip)

set(CMAKE_EXE_LINKER_FLAGS    "" CACHE INTERNAL "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "" CACHE INTERNAL "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "" CACHE INTERNAL "" FORCE)

set(CMAKE_FIND_ROOT_PATH $ENV{WIND_SDK})
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)


set(CMAKE_CXX_FLAGS           "-I${CMAKE_BINARY_DIR} ${CMAKE_CXX_FLAGS}")
set(CMAKE_C_FLAGS             "-I${CMAKE_BINARY_DIR} ${CMAKE_C_FLAGS}" )
